/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Standalone, i386, gcc */
/* Command for C compiler:
   i686-elf-gcc.exe -c -w -mno-ms-bitfields -m32 -std=gnu99 -ffreestanding -fno-stack-protector -nostdlib -O2 -Wall -Wextra -O3 -fno-strict-aliasing  -IC:\msys64\home\Ikem\projects\nimkernel\src\runtime -IC:\msys64\home\Ikem\projects\nimkernel\src\runtime\include -o C:\msys64\home\Ikem\projects\nimkernel\src\nimcache\boot.o C:\msys64\home\Ikem\projects\nimkernel\src\nimcache\boot.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
N_NIMCALL(void, kernel_start)(void) __attribute__((naked));
N_LIB_PRIVATE N_NIMCALL(void, kernel_setup_PH9bK52s4ytbzskvbPXa26Q)(void);

N_LIB_PRIVATE N_NIMCALL(void, kernel_setup_PH9bK52s4ytbzskvbPXa26Q)(void) {
}

N_NIMCALL(void, kernel_start)(void) {
	asm(".set ALIGN,    1 << 0\n"
);
	asm(".set MEMINFO,  1 << 1\n"
);
	asm(".set FLAGS,    ALIGN | MEMINFO\n"
);
	asm(".set MAGIC,    0x1BADB002\n"
);
	asm(".set CHECKSUM, -(MAGIC + FLAGS)\n"
);
	asm(".section .multiboot\n"
);
	asm(".align 4\n"
);
	asm(".long MAGIC\n"
);
	asm(".long FLAGS\n"
);
	asm(".long CHECKSUM\n"
);
	asm(".section .bss\n"
);
	asm(".align 16\n"
);
	asm("stack_bottom:\n"
);
	asm(".skip 16384\n"
);
	asm("stack_top:\n"
);
	asm(".section .text\n"
);
	asm(".global kernel_start\n"
);
	asm(".type kernel_start, @function\n"
);
	asm("kernel_start:\n"
);
	asm("  mov $stack_top, %esp\n"
);
	kernel_setup_PH9bK52s4ytbzskvbPXa26Q();
	asm("  call main\n"
);
	asm("  cli\n"
);
	asm("1:	hlt\n"
);
	asm("  jmp 1b\n"
);
	asm(".size kernel_start, . - kernel_start\n"
);
}

NIM_EXTERNC N_NOINLINE(void, unknown_bootInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, unknown_bootDatInit000)(void) {
}

