/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Standalone, i386, gcc */
/* Command for C compiler:
   i686-elf-gcc.exe -c -w -mno-ms-bitfields -m32 -std=gnu99 -ffreestanding -fno-stack-protector -nostdlib -O2 -Wall -Wextra -O3 -fno-strict-aliasing  -IC:\msys64\home\Ikem\projects\nimkernel\src\runtime -IC:\msys64\home\Ikem\projects\nimkernel\src\runtime\include -o C:\msys64\home\Ikem\projects\nimkernel\src\nimcache\global.o C:\msys64\home\Ikem\projects\nimkernel\src\nimcache\global.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Entry_7s47oEqE7AFv9aU2NaCUlLA tyObject_Entry_7s47oEqE7AFv9aU2NaCUlLA;
typedef struct tyObject_Pointer_mdU2r6vuOa3qYP3x0Cg1kQ tyObject_Pointer_mdU2r6vuOa3qYP3x0Cg1kQ;
struct __attribute__((__packed__)) tyObject_Entry_7s47oEqE7AFv9aU2NaCUlLA {
NU16 limit_low;
NU16 base_low;
NU8 base_middle;
NU8 access;
NU8 granularity;
NU8 base_high;
};
typedef tyObject_Entry_7s47oEqE7AFv9aU2NaCUlLA tyArray_MAdO9bFlDEHhtBd4G2CEabA[5];
struct __attribute__((__packed__)) tyObject_Pointer_mdU2r6vuOa3qYP3x0Cg1kQ {
NU16 limit;
NU32 base;
};
tyArray_MAdO9bFlDEHhtBd4G2CEabA gdtEntries_4OsvXbIppR6c78SjZVeVnA;
tyObject_Pointer_mdU2r6vuOa3qYP3x0Cg1kQ gdtPointer_S5Mbuln2rOXNFr7ZVTrP3g;
NIM_EXTERNC N_NOINLINE(void, unknown_globalInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, unknown_globalDatInit000)(void) {
}

