/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Standalone, i386, gcc */
/* Command for C compiler:
   i686-elf-gcc.exe -c -w -mno-ms-bitfields -m32 -std=gnu99 -ffreestanding -fno-stack-protector -nostdlib -O2 -Wall -Wextra -O3 -fno-strict-aliasing  -IC:\msys64\home\Ikem\projects\nimkernel\src\runtime -IC:\msys64\home\Ikem\projects\nimkernel\src\runtime\include -o C:\msys64\home\Ikem\projects\nimkernel\src\nimcache\main.o C:\msys64\home\Ikem\projects\nimkernel\src\nimcache\main.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
N_LIB_PRIVATE N_NIMCALL(void, main_9cku33tvANHm87a2gL2qUHQ)(void);
N_LIB_PRIVATE N_NIMCALL(void, putChar_2Ph2WtyR6XT6JOH49aKTtrQ)(NIM_CHAR c);
NIM_EXTERNC N_NOINLINE(void, unknown_portInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_portDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_vgaInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_vgaDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_panicoverrideInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_panicoverrideDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_utilInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_utilDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_globalInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_globalDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_dtInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_dtDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_bootInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_bootDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, mainDatInit000)(void);

N_LIB_PRIVATE N_NIMCALL(void, main_9cku33tvANHm87a2gL2qUHQ)(void) {
	{
		NIM_CHAR c;
		NI res;
		c = (NIM_CHAR)0;
		res = ((NI) 97);
		{
			while (1) {
				if (!(res <= ((NI) 121))) goto LA3;
				c = ((NIM_CHAR) (res));
				putChar_2Ph2WtyR6XT6JOH49aKTtrQ(c);
				putChar_2Ph2WtyR6XT6JOH49aKTtrQ(10);
				res += ((NI) 1);
			} LA3: ;
		}
	}
	putChar_2Ph2WtyR6XT6JOH49aKTtrQ(122);
}
void PreMainInner(void) {
	systemInit000();
	unknown_portDatInit000();
	unknown_vgaDatInit000();
	unknown_panicoverrideDatInit000();
	unknown_utilDatInit000();
	unknown_globalDatInit000();
	unknown_dtDatInit000();
	unknown_bootDatInit000();
	mainDatInit000();
	unknown_portInit000();
	unknown_vgaInit000();
	unknown_panicoverrideInit000();
	unknown_utilInit000();
	unknown_globalInit000();
	unknown_dtInit000();
	unknown_bootInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
}

int main(void) {
	NimMain();
	return 0;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	main_9cku33tvANHm87a2gL2qUHQ();
}

NIM_EXTERNC N_NOINLINE(void, mainDatInit000)(void) {
}

