/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Standalone, i386, gcc */
/* Command for C compiler:
   i686-elf-gcc.exe -c -w -mno-ms-bitfields -m32 -std=gnu99 -ffreestanding -fno-stack-protector -nostdlib -O2 -Wall -Wextra -O3 -fno-strict-aliasing  -IC:\msys64\home\Ikem\projects\nimkernel\src\runtime -IC:\msys64\home\Ikem\projects\nimkernel\src\runtime\include -o C:\msys64\home\Ikem\projects\nimkernel\src\nimcache\port.o C:\msys64\home\Ikem\projects\nimkernel\src\nimcache\port.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef NU16 tyEnum_Port_0Kt8bpmECE9cfZ4mRh1Qcng;

N_LIB_PRIVATE N_NIMCALL(void, write_xeLnbsD0M5kgXb0SYtOtJg)(tyEnum_Port_0Kt8bpmECE9cfZ4mRh1Qcng port, NU8 value) {
	asm("outb %0, %1\n"
    : :"a"(value), "Nd"(port)
);
}
NIM_EXTERNC N_NOINLINE(void, unknown_portInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, unknown_portDatInit000)(void) {
}

