/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Standalone, i386, gcc */
/* Command for C compiler:
   i686-elf-gcc.exe -c -w -mno-ms-bitfields -m32 -std=gnu99 -ffreestanding -fno-stack-protector -nostdlib -O2 -Wall -Wextra -O3 -fno-strict-aliasing  -IC:\msys64\home\Ikem\projects\nimkernel\src\runtime -IC:\msys64\home\Ikem\projects\nimkernel\src\runtime\include -o C:\msys64\home\Ikem\projects\nimkernel\src\nimcache\system.o C:\msys64\home\Ikem\projects\nimkernel\src\nimcache\system.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct Exception Exception;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyTuple_J8Kl9a9cW6PEnQ5hdpomtkew tyTuple_J8Kl9a9cW6PEnQ5hdpomtkew;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_tUJGHojtqYYDQvCBuRvw9aQ tySequence_tUJGHojtqYYDQvCBuRvw9aQ;
typedef struct tyObject_StackTraceEntry_GMehuweJp9agCJD7BWrbRDQ tyObject_StackTraceEntry_GMehuweJp9agCJD7BWrbRDQ;
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc_GzFyMf8B5aWLmxFUtABXJg) (Exception* e);
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_Color_DBui5iA14VOSbWT6b1mp7g;
struct tyTuple_J8Kl9a9cW6PEnQ5hdpomtkew {
tyEnum_Color_DBui5iA14VOSbWT6b1mp7g Field0;
tyEnum_Color_DBui5iA14VOSbWT6b1mp7g Field1;
};
typedef NU8 tyEnum_TNimKind_9bVdDrHQyMKyUtP809aaTyGA;
typedef NU8 tySet_tyEnum_TNimTypeFlag_uMdLtRhl0kCKyvbnATne5g;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_9bVdDrHQyMKyUtP809aaTyGA kind;
tySet_tyEnum_TNimTypeFlag_uMdLtRhl0kCKyvbnATne5g flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_tUJGHojtqYYDQvCBuRvw9aQ* trace;
Exception* up;
};
typedef NU8 tyEnum_TNimNodeKind_qUOGoiZdGzIiA0a1AvLfaA;
struct TNimNode {
tyEnum_TNimNodeKind_qUOGoiZdGzIiA0a1AvLfaA kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_StackTraceEntry_GMehuweJp9agCJD7BWrbRDQ {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence_tUJGHojtqYYDQvCBuRvw9aQ {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_GMehuweJp9agCJD7BWrbRDQ data[SEQ_DECL_SIZE];
};
N_CDECL(void, abort)(void) __attribute__((noreturn));
N_LIB_PRIVATE N_NIMCALL(void, panic_xmJlSb0pN9bKQ1if3tnwW9aw)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NI, getRow_6K57UWvAw49bPLOc12WipXw)(void);
N_LIB_PRIVATE N_NIMCALL(NI, getColumn_F1AfupIoFBcrdgymM230lA)(void);
N_LIB_PRIVATE N_NIMCALL(tyTuple_J8Kl9a9cW6PEnQ5hdpomtkew, getColor_Q4VdXMD4WSjxABnSNIhUjw)(void);
N_LIB_PRIVATE N_NIMCALL(void, setRow_qM09cpMcRwnJydPHBHwFfAQ)(NI row);
N_LIB_PRIVATE N_NIMCALL(void, setColumn_k9bijFUbgjqa1rggBjj14fA)(NI col);
N_LIB_PRIVATE N_NIMCALL(void, setColor_Kdoh0zopRp7hZN89boRbtmQ)(tyEnum_Color_DBui5iA14VOSbWT6b1mp7g fg, tyEnum_Color_DBui5iA14VOSbWT6b1mp7g bg);
N_LIB_PRIVATE N_NIMCALL(void, rawoutput_xmJlSb0pN9bKQ1if3tnwW9aw_2)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void, writeLine_NPU2KG0vDoiIKGG9aWp3JoQ)(NimStringDesc* data);
N_CDECL(void, exit)(NI status) __attribute__((noreturn));
N_CDECL(size_t, strlen)(NCSTRING str);
N_CDECL(int, memcmp)(void* s1, void* s2, size_t n);
N_CDECL(void*, memcpy)(void* dest, void* src, size_t n);
N_CDECL(void*, memset)(void* s, int c, size_t n);
N_CDECL(void*, memmove)(void* dest, void* src, size_t n);
NIM_BOOL nimvm_E09bA5REobN1HHNn54M1lWw;
NI nim_program_result;
tyProc_GzFyMf8B5aWLmxFUtABXJg globalRaiseHook_uSgtQGs9cg0OV9aUZzfLCggA;
tyProc_GzFyMf8B5aWLmxFUtABXJg localRaiseHook_GBZEjb2oijZzm3y3fFrOIw;
tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ outOfMemHook_pnOJCzTYsIbQd7UXXht2ug;
STRING_LITERAL(TM_9b1laNaHQpMx8rf3VZ1EoRw_2, "an error has occured", 20);
STRING_LITERAL(TM_9b1laNaHQpMx8rf3VZ1EoRw_3, "exit: success", 13);
STRING_LITERAL(TM_9b1laNaHQpMx8rf3VZ1EoRw_4, "exit: failure", 13);

N_LIB_PRIVATE N_NIMCALL(void, rawoutput_xmJlSb0pN9bKQ1if3tnwW9aw_2)(NimStringDesc* s) {
	writeLine_NPU2KG0vDoiIKGG9aWp3JoQ(s);
}

N_LIB_PRIVATE N_NIMCALL(void, panic_xmJlSb0pN9bKQ1if3tnwW9aw)(NimStringDesc* s) {
	NI row;
	NI col;
	tyTuple_J8Kl9a9cW6PEnQ5hdpomtkew T1_;
	tyEnum_Color_DBui5iA14VOSbWT6b1mp7g fg;
	tyEnum_Color_DBui5iA14VOSbWT6b1mp7g bg;
	row = getRow_6K57UWvAw49bPLOc12WipXw();
	col = getColumn_F1AfupIoFBcrdgymM230lA();
	T1_ = getColor_Q4VdXMD4WSjxABnSNIhUjw();
	fg = T1_.Field0;
	bg = T1_.Field1;
	setRow_qM09cpMcRwnJydPHBHwFfAQ(((NI) 24));
	setColumn_k9bijFUbgjqa1rggBjj14fA(((NI) 0));
	setColor_Kdoh0zopRp7hZN89boRbtmQ(((tyEnum_Color_DBui5iA14VOSbWT6b1mp7g) 4), ((tyEnum_Color_DBui5iA14VOSbWT6b1mp7g) 15));
	rawoutput_xmJlSb0pN9bKQ1if3tnwW9aw_2(s);
	setRow_qM09cpMcRwnJydPHBHwFfAQ(row);
	setColumn_k9bijFUbgjqa1rggBjj14fA(col);
	setColor_Kdoh0zopRp7hZN89boRbtmQ(fg, bg);
}

N_CDECL(void, abort)(void) {
	panic_xmJlSb0pN9bKQ1if3tnwW9aw(((NimStringDesc*) &TM_9b1laNaHQpMx8rf3VZ1EoRw_2));
	{
		while (1) {
		}
	}
}

N_CDECL(void, exit)(NI status) {
	switch (status) {
	case ((NI) 0):
	{
		panic_xmJlSb0pN9bKQ1if3tnwW9aw(((NimStringDesc*) &TM_9b1laNaHQpMx8rf3VZ1EoRw_3));
	}
	break;
	case ((NI) 1):
	{
		panic_xmJlSb0pN9bKQ1if3tnwW9aw(((NimStringDesc*) &TM_9b1laNaHQpMx8rf3VZ1EoRw_4));
	}
	break;
	default:
	{
	}
	break;
	}
	{
		while (1) {
		}
	}
}

N_CDECL(size_t, strlen)(NCSTRING str) {
	size_t result;
	NI i;
	result = (size_t)0;
	i = ((NI) 0);
	{
		while (1) {
			if (!!(((NU8)(str[i]) == (NU8)(0)))) goto LA2;
			result += ((NI) 1);
			i += ((NI) 1);
		} LA2: ;
	}
	return result;
}

N_CDECL(int, memcmp)(void* s1, void* s2, size_t n) {
	int result;
	NIM_CHAR* s1_2;
	NIM_CHAR* s2_2;
{	result = (int)0;
	result = ((int) 0);
	s1_2 = ((NIM_CHAR*) (s1));
	s2_2 = ((NIM_CHAR*) (s2));
	{
		NI idx;
		NI colontmp_;
		NI res;
		idx = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(n - ((NI) 1));
		res = ((NI) 0);
		{
			while (1) {
				if (!(res <= colontmp_)) goto LA3;
				idx = res;
				{
					if (!!(((NU8)(s1_2[(idx)- 0]) == (NU8)(s2_2[(idx)- 0])))) goto LA6_;
					result = (NI32)(((int) (((NU8)(s1_2[(idx)- 0])))) - ((int) (((NU8)(s2_2[(idx)- 0])))));
					goto BeforeRet_;
				}
				LA6_: ;
				res += ((NI) 1);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	return result;
}

N_CDECL(void*, memcpy)(void* dest, void* src, size_t n) {
	void* result;
	NIM_CHAR* dest_2;
	NIM_CHAR* src_2;
	result = (void*)0;
	result = dest;
	dest_2 = ((NIM_CHAR*) (dest));
	src_2 = ((NIM_CHAR*) (src));
	{
		NI idx;
		NI colontmp_;
		NI res;
		idx = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(n - ((NI) 1));
		res = ((NI) 0);
		{
			while (1) {
				if (!(res <= colontmp_)) goto LA3;
				idx = res;
				dest_2[(idx)- 0] = src_2[(idx)- 0];
				res += ((NI) 1);
			} LA3: ;
		}
	}
	return result;
}

N_CDECL(void*, memset)(void* s, int c, size_t n) {
	void* result;
	NIM_CHAR* str;
	result = (void*)0;
	result = s;
	str = ((NIM_CHAR*) (s));
	{
		NI idx;
		NI colontmp_;
		NI res;
		idx = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(n - ((NI) 1));
		res = ((NI) 0);
		{
			while (1) {
				if (!(res <= colontmp_)) goto LA3;
				idx = res;
				str[(idx)- 0] = ((unsigned char) (c));
				res += ((NI) 1);
			} LA3: ;
		}
	}
	return result;
}

N_CDECL(void*, memmove)(void* dest, void* src, size_t n) {
	void* result;
	NIM_BOOL direction;
	NIM_CHAR* dest_2;
	NIM_CHAR* src_2;
	result = (void*)0;
	result = dest;
	direction = (src < dest);
	dest_2 = ((NIM_CHAR*) (dest));
	src_2 = ((NIM_CHAR*) (src));
	{
		if (!direction) goto LA3_;
		{
			NI idx;
			NI colontmp_;
			NI res;
			idx = (NI)0;
			colontmp_ = (NI)0;
			colontmp_ = (NI)(n - ((NI) 1));
			res = colontmp_;
			{
				while (1) {
					if (!(((NI) 0) <= res)) goto LA7;
					idx = res;
					dest_2[(idx)- 0] = src_2[(idx)- 0];
					res -= ((NI) 1);
				} LA7: ;
			}
		}
	}
	goto LA1_;
	LA3_: ;
	{
		{
			NI idx_2;
			NI colontmp__2;
			NI res_2;
			idx_2 = (NI)0;
			colontmp__2 = (NI)0;
			colontmp__2 = (NI)(n - ((NI) 1));
			res_2 = ((NI) 0);
			{
				while (1) {
					if (!(res_2 <= colontmp__2)) goto LA11;
					idx_2 = res_2;
					dest_2[(idx_2)- 0] = src_2[(idx_2)- 0];
					res_2 += ((NI) 1);
				} LA11: ;
			}
		}
	}
	LA1_: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void) {
	nimvm_E09bA5REobN1HHNn54M1lWw = NIM_FALSE;
}

NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void) {
}

