/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Standalone, i386, gcc */
/* Command for C compiler:
   i686-elf-gcc.exe -c -w -mno-ms-bitfields -m32 -std=gnu99 -ffreestanding -fno-stack-protector -nostdlib -O2 -Wall -Wextra -O3 -fno-strict-aliasing  -IC:\msys64\home\Ikem\projects\nimkernel\src\runtime -IC:\msys64\home\Ikem\projects\nimkernel\src\runtime\include -o C:\msys64\home\Ikem\projects\nimkernel\src\nimcache\vga.o C:\msys64\home\Ikem\projects\nimkernel\src\nimcache\vga.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_J8Kl9a9cW6PEnQ5hdpomtkew tyTuple_J8Kl9a9cW6PEnQ5hdpomtkew;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef NU8 tyEnum_Color_DBui5iA14VOSbWT6b1mp7g;
struct tyTuple_J8Kl9a9cW6PEnQ5hdpomtkew {
tyEnum_Color_DBui5iA14VOSbWT6b1mp7g Field0;
tyEnum_Color_DBui5iA14VOSbWT6b1mp7g Field1;
};
typedef NU16 tyEnum_Port_0Kt8bpmECE9cfZ4mRh1Qcng;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, init_cfcj4iAUPXtBmnK9cWBZrWw)(void);
N_LIB_PRIVATE N_NIMCALL(NU8, entryColor_OhhbbaHW2b8ot0NyxeOKiQ)(tyEnum_Color_DBui5iA14VOSbWT6b1mp7g fg, tyEnum_Color_DBui5iA14VOSbWT6b1mp7g bg);
N_LIB_PRIVATE N_NIMCALL(void, clear_cfcj4iAUPXtBmnK9cWBZrWw_2)(void);
N_LIB_PRIVATE N_NIMCALL(NU16, entry_w03LLgJI7UgxRNs9cbGeARA)(NIM_CHAR uc, NU8 color);
N_LIB_PRIVATE N_NIMCALL(void, updateCursor_cfcj4iAUPXtBmnK9cWBZrWw_3)(void);
N_LIB_PRIVATE N_NIMCALL(void, moveCursor_hOU4JQPrPK3X9bYuW7X1knA)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void, write_xeLnbsD0M5kgXb0SYtOtJg)(tyEnum_Port_0Kt8bpmECE9cfZ4mRh1Qcng port, NU8 value);
N_LIB_PRIVATE N_NIMCALL(void, write_NPU2KG0vDoiIKGG9aWp3JoQ_2)(NimStringDesc* data);
N_LIB_PRIVATE N_NIMCALL(void, putChar_2Ph2WtyR6XT6JOH49aKTtrQ)(NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(void, handleEscape_2Ph2WtyR6XT6JOH49aKTtrQ_2)(NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(void, putEntryAt_VydswypLm4cQ3yFMoj8Nsg)(NIM_CHAR c, NI x, NI y);
NU16* volatile terminalBuffer_TOAH8RsLf9aPC9cY7L7BNVSw;
NI terminalRow_q9amUCtr7p4uNOJmyszIjtQ;
NI terminalColumn_g9aTaduxezebRculwXGR9byA;
tyEnum_Color_DBui5iA14VOSbWT6b1mp7g terminalForeGround_lZBa1LNQ5qox5qtUirGq8w;
tyEnum_Color_DBui5iA14VOSbWT6b1mp7g terminalBackGround_e5ZQlQiIpweezsMjbazy1g;
NU8 terminalColor_GCsPtnMAtCT4pPZJlJFoPQ;

N_LIB_PRIVATE N_NIMCALL(NU8, entryColor_OhhbbaHW2b8ot0NyxeOKiQ)(tyEnum_Color_DBui5iA14VOSbWT6b1mp7g fg, tyEnum_Color_DBui5iA14VOSbWT6b1mp7g bg) {
	NU8 result;
{	result = (NU8)0;
	result = (NU8)(((NU8) (fg)) | (NU8)((NU32)(((NU8) (bg))) << (NU32)(((NI) 4))));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NU16, entry_w03LLgJI7UgxRNs9cbGeARA)(NIM_CHAR uc, NU8 color) {
	NU16 result;
{	result = (NU16)0;
	result = (NU16)(((NU16) (((NU8)(uc)))) | (NU16)((NU32)(((NU16) (color))) << (NU32)(((NI) 8))));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, clear_cfcj4iAUPXtBmnK9cWBZrWw_2)(void) {
	{
		NI i;
		NI res;
		i = (NI)0;
		res = ((NI) 0);
		{
			while (1) {
				if (!(res <= ((NI) 1999))) goto LA3;
				i = res;
				terminalBuffer_TOAH8RsLf9aPC9cY7L7BNVSw[(i)- 0] = entry_w03LLgJI7UgxRNs9cbGeARA(32, terminalColor_GCsPtnMAtCT4pPZJlJFoPQ);
				res += ((NI) 1);
			} LA3: ;
		}
	}
}

N_LIB_PRIVATE N_NIMCALL(void, init_cfcj4iAUPXtBmnK9cWBZrWw)(void) {
	terminalRow_q9amUCtr7p4uNOJmyszIjtQ = ((NI) 0);
	terminalColumn_g9aTaduxezebRculwXGR9byA = ((NI) 0);
	terminalForeGround_lZBa1LNQ5qox5qtUirGq8w = ((tyEnum_Color_DBui5iA14VOSbWT6b1mp7g) 7);
	terminalBackGround_e5ZQlQiIpweezsMjbazy1g = ((tyEnum_Color_DBui5iA14VOSbWT6b1mp7g) 8);
	terminalColor_GCsPtnMAtCT4pPZJlJFoPQ = entryColor_OhhbbaHW2b8ot0NyxeOKiQ(terminalForeGround_lZBa1LNQ5qox5qtUirGq8w, terminalBackGround_e5ZQlQiIpweezsMjbazy1g);
	terminalBuffer_TOAH8RsLf9aPC9cY7L7BNVSw = ((NU16*) 753664);
	clear_cfcj4iAUPXtBmnK9cWBZrWw_2();
}

N_LIB_PRIVATE N_NIMCALL(NI, getRow_6K57UWvAw49bPLOc12WipXw)(void) {
	NI result;
	result = (NI)0;
	result = terminalRow_q9amUCtr7p4uNOJmyszIjtQ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, getColumn_F1AfupIoFBcrdgymM230lA)(void) {
	NI result;
	result = (NI)0;
	result = terminalColumn_g9aTaduxezebRculwXGR9byA;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_J8Kl9a9cW6PEnQ5hdpomtkew, getColor_Q4VdXMD4WSjxABnSNIhUjw)(void) {
	tyTuple_J8Kl9a9cW6PEnQ5hdpomtkew result;
	memset((void*)(&result), 0, sizeof(result));
	result.Field0 = terminalForeGround_lZBa1LNQ5qox5qtUirGq8w;
	result.Field1 = terminalBackGround_e5ZQlQiIpweezsMjbazy1g;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, moveCursor_hOU4JQPrPK3X9bYuW7X1knA)(NI x, NI y) {
	NU16 pos;
	pos = ((NU16) ((NI)((NI)(y * ((NI) 80)) + x)));
	write_xeLnbsD0M5kgXb0SYtOtJg(((tyEnum_Port_0Kt8bpmECE9cfZ4mRh1Qcng) 980), ((NU8) 14));
	write_xeLnbsD0M5kgXb0SYtOtJg(((tyEnum_Port_0Kt8bpmECE9cfZ4mRh1Qcng) 981), ((NU8) ((NU16)((NU16)((NU16)(pos) >> (NU32)(((NI) 8))) & ((NI) 255)))));
	write_xeLnbsD0M5kgXb0SYtOtJg(((tyEnum_Port_0Kt8bpmECE9cfZ4mRh1Qcng) 980), ((NU8) 15));
	write_xeLnbsD0M5kgXb0SYtOtJg(((tyEnum_Port_0Kt8bpmECE9cfZ4mRh1Qcng) 981), ((NU8) ((NU16)(pos & ((NI) 255)))));
}

N_LIB_PRIVATE N_NIMCALL(void, updateCursor_cfcj4iAUPXtBmnK9cWBZrWw_3)(void) {
	moveCursor_hOU4JQPrPK3X9bYuW7X1knA(((NI) (terminalColumn_g9aTaduxezebRculwXGR9byA)), ((NI) (terminalRow_q9amUCtr7p4uNOJmyszIjtQ)));
}

N_LIB_PRIVATE N_NIMCALL(void, setRow_qM09cpMcRwnJydPHBHwFfAQ)(NI row) {
	terminalRow_q9amUCtr7p4uNOJmyszIjtQ = row;
	updateCursor_cfcj4iAUPXtBmnK9cWBZrWw_3();
}

N_LIB_PRIVATE N_NIMCALL(void, setColumn_k9bijFUbgjqa1rggBjj14fA)(NI col) {
	terminalColumn_g9aTaduxezebRculwXGR9byA = col;
	updateCursor_cfcj4iAUPXtBmnK9cWBZrWw_3();
}

N_LIB_PRIVATE N_NIMCALL(void, setColor_Kdoh0zopRp7hZN89boRbtmQ)(tyEnum_Color_DBui5iA14VOSbWT6b1mp7g fg, tyEnum_Color_DBui5iA14VOSbWT6b1mp7g bg) {
	terminalForeGround_lZBa1LNQ5qox5qtUirGq8w = fg;
	terminalBackGround_e5ZQlQiIpweezsMjbazy1g = bg;
	terminalColor_GCsPtnMAtCT4pPZJlJFoPQ = entryColor_OhhbbaHW2b8ot0NyxeOKiQ(terminalForeGround_lZBa1LNQ5qox5qtUirGq8w, terminalBackGround_e5ZQlQiIpweezsMjbazy1g);
}

N_LIB_PRIVATE N_NIMCALL(void, handleEscape_2Ph2WtyR6XT6JOH49aKTtrQ_2)(NIM_CHAR c) {
	switch (((NU8)(c))) {
	case 8:
	{
		terminalColumn_g9aTaduxezebRculwXGR9byA -= ((NI) 1);
	}
	break;
	case 10:
	{
		terminalRow_q9amUCtr7p4uNOJmyszIjtQ += ((NI) 1);
		terminalColumn_g9aTaduxezebRculwXGR9byA = ((NI) 0);
	}
	break;
	case 13:
	{
		terminalColumn_g9aTaduxezebRculwXGR9byA = ((NI) 0);
	}
	break;
	case 9:
	{
		terminalColumn_g9aTaduxezebRculwXGR9byA += ((NI) 4);
	}
	break;
	default:
	{
	}
	break;
	}
}

N_LIB_PRIVATE N_NIMCALL(void, putEntryAt_VydswypLm4cQ3yFMoj8Nsg)(NIM_CHAR c, NI x, NI y) {
	terminalBuffer_TOAH8RsLf9aPC9cY7L7BNVSw[((NI)((NI)(y * ((NI) 80)) + x))- 0] = entry_w03LLgJI7UgxRNs9cbGeARA(c, terminalColor_GCsPtnMAtCT4pPZJlJFoPQ);
}

N_LIB_PRIVATE N_NIMCALL(void, putChar_2Ph2WtyR6XT6JOH49aKTtrQ)(NIM_CHAR c) {
	{
		if (!(((NU8)(c)) == ((NU8)(8)) || ((NU8)(c)) == ((NU8)(10)) || ((NU8)(c)) == ((NU8)(13)) || ((NU8)(c)) == ((NU8)(9)))) goto LA3_;
		handleEscape_2Ph2WtyR6XT6JOH49aKTtrQ_2(c);
	}
	goto LA1_;
	LA3_: ;
	{
		putEntryAt_VydswypLm4cQ3yFMoj8Nsg(c, ((NI) (terminalColumn_g9aTaduxezebRculwXGR9byA)), ((NI) (terminalRow_q9amUCtr7p4uNOJmyszIjtQ)));
		terminalColumn_g9aTaduxezebRculwXGR9byA += ((NI) 1);
	}
	LA1_: ;
	{
		if (!(((NI) 80) <= ((NI) (terminalColumn_g9aTaduxezebRculwXGR9byA)))) goto LA8_;
		terminalColumn_g9aTaduxezebRculwXGR9byA = ((NI) 0);
		terminalRow_q9amUCtr7p4uNOJmyszIjtQ += ((NI) 1);
	}
	LA8_: ;
	{
		NU16 blank;
		NI line;
		if (!(((NI) 25) <= ((NI) (terminalRow_q9amUCtr7p4uNOJmyszIjtQ)))) goto LA12_;
		blank = entry_w03LLgJI7UgxRNs9cbGeARA(32, terminalColor_GCsPtnMAtCT4pPZJlJFoPQ);
		line = ((NI) 1920);
		{
			NI i;
			NI colontmp_;
			NI res;
			i = (NI)0;
			colontmp_ = (NI)0;
			colontmp_ = (NI)(line - ((NI) 1));
			res = ((NI) 0);
			{
				while (1) {
					if (!(res <= colontmp_)) goto LA16;
					i = res;
					terminalBuffer_TOAH8RsLf9aPC9cY7L7BNVSw[(i)- 0] = terminalBuffer_TOAH8RsLf9aPC9cY7L7BNVSw[((NI)(i + ((NI) 80)))- 0];
					res += ((NI) 1);
				} LA16: ;
			}
		}
		{
			NI i_2;
			NI res_2;
			i_2 = (NI)0;
			res_2 = line;
			{
				while (1) {
					if (!(res_2 <= ((NI) 1999))) goto LA19;
					i_2 = res_2;
					terminalBuffer_TOAH8RsLf9aPC9cY7L7BNVSw[(i_2)- 0] = blank;
					res_2 += ((NI) 1);
				} LA19: ;
			}
		}
		terminalRow_q9amUCtr7p4uNOJmyszIjtQ = ((NI) 24);
	}
	LA12_: ;
	updateCursor_cfcj4iAUPXtBmnK9cWBZrWw_3();
}

N_LIB_PRIVATE N_NIMCALL(void, write_NPU2KG0vDoiIKGG9aWp3JoQ_2)(NimStringDesc* data) {
	{
		NIM_CHAR c;
		NCSTRING colontmp_;
		NI i;
		c = (NIM_CHAR)0;
		colontmp_ = (NCSTRING)0;
		colontmp_ = data->data;
		i = ((NI) 0);
		{
			while (1) {
				if (!!(((NU8)(colontmp_[i]) == (NU8)(0)))) goto LA3;
				c = colontmp_[i];
				putChar_2Ph2WtyR6XT6JOH49aKTtrQ(c);
				i += ((NI) 1);
			} LA3: ;
		}
	}
}

N_LIB_PRIVATE N_NIMCALL(void, writeLine_NPU2KG0vDoiIKGG9aWp3JoQ)(NimStringDesc* data) {
	write_NPU2KG0vDoiIKGG9aWp3JoQ_2(data);
	terminalRow_q9amUCtr7p4uNOJmyszIjtQ += ((NI) 1);
	terminalColumn_g9aTaduxezebRculwXGR9byA = ((NI) 0);
}
NIM_EXTERNC N_NOINLINE(void, unknown_vgaInit000)(void) {
	init_cfcj4iAUPXtBmnK9cWBZrWw();
}

NIM_EXTERNC N_NOINLINE(void, unknown_vgaDatInit000)(void) {
}

